select 
CAST(e.SHOT_SPEED * 200 as INT) as SSBounds,
HEALTH,
FIRE_RATE,
count(ENEMY_ID),
avg(e.HITS)
from ENEMIES e 
inner JOIN WAVES w on w.WAVE_ID = e.WAVE_ID 
AND w.TEST_ID = e.TEST_ID
WHERE e.TEST_ID = 78 --AND ENEMY_COUNT = 1
GROUP by FIRE_RATE
 