SELECT *, 
ENEMIES.HITS as EnemyHits,
WAVES.HITS as WaveHits,
HEALTH*SHOT_SPEED/FIRE_RATE as Inputs, 
1.0*ENEMIES.HITS/LIFETIME as HitRate, 
1.0*ENEMIES.HITS/ENEMY_COUNT as HitCredit1, 
1.0*ENEMIES.HITS/WAVES.HITS as HitCredit2, 
1.0*ENEMIES.HITS/WAVES.HITS/ENEMY_COUNT as HitCredit3 
FROM ENEMIES
INNER JOIN WAVES on WAVES.WAVE_ID = ENEMIES.WAVE_ID AND WAVES.TEST_ID = ENEMIES.TEST_ID
WHERE WAVES.TEST_ID = 71;